686 logging typos
FOLIO-FSE/folio_migration_tools pull request #688
Opened 2023-09-28 19:56 UTC by kevinpowell1

2023-09-28 19:57 UTC, kevinpowell1 reviewed
more typo fixes

2023-09-29 03:57 UTC, bltravis commented on pyproject.toml
@kevinpowell1 Looks like this snuck in. Can we remove it, please?

2023-09-29 04:01 UTC, bltravis requested changes
A couple questions inline.

2023-09-29 04:01 UTC, bltravis commented on src/folio_migration_tools/mapping_file_transformation/organization_mapper.py
> +        self.address_categories_map = RefDataMapping(
This doesn't seem like fixing typos. Was this included intentionally?

2023-10-09 03:51 UTC, bltravis commented
@kevinpowell1 Can you have a look at this?

2024-11-30 03:41 UTC, bltravis commented
This was fixed in #804

2024-11-30 03:41 UTC, closed without merging